### PR TITLE
Fixes #31 - adds event extent button

### LINKED ISSUE #31: map home extent button
Add "Home" button to reset extent to event extent

### PR DESCRIPTION
**Pull request by 09Kathy**
Not sure if there are specific styles we should be using. This is what it looks like now:
image

### CODE REVIEW

**Comment by lprivette** [comment]
I wonder if it should be a little 'home' icon underneath the zoom control? like where the magnifying glass is
image.

leaflet may make this difficult though

**Comment by lprivette** [comment]
Or maybe even as a button next to the "Map Filters" text

**Comment by 09Kathy** [comment]
Yeah, I'll try that!

**Comment by 09Kathy** [comment]
Button looks like this now: 
image

**Review by lprivette — APPROVED** [review]

**Pull request merged**
