### PR TITLE
224

### PR DESCRIPTION
**Pull request by Abigail770**
- Fixed bug with results table sometimes displaying blank table
- Fixed mobile responsiveness of results table/results modal
- Restyled results/results modal tables
- Reordered columns in result details table.  @jprokopec does the column order below make sense for a user?
image

### CODE REVIEW

**Comment by jprokopec** [comment]
@Abigail770 I like the column order you have there. It might make sense to highlight the "Deployed" sensors so they are easier to see? Do we ever have other sensor types listed other than Pressure Transducer? If it is the only one used I am not sure that column is needed then.

**Comment by Abigail770** [comment]
@jprokopec there are 5 different options for sensor type (the results can be filtered by sensor type in the left sidebar).  We can definitely highlight the Deployed sensors.  One idea could be to add an icon (like a checkmark) to the status cell if the sensor is deployed:
image

**Comment by jprokopec** [comment]
@Abigail770 I like the checkmark. It really highlights that it is still deployed which could remind the user to update the status. 

Sounds good about the sensors. Nevermind on that comment then.

**Comment by lprivette** [comment]
It looks like the "no sensors" modal is displaying before the sensors data finishes loading and that table pops up https://recordit.co/9v0cbcTkUr

how about we open the modal with the progress-spinner going, and then once sensorData length is resolved display the relevant text using ng-ifs on those elements?

**Review by lprivette — APPROVED** [review]

**Comment by chaqazarad** [comment]
> @Abigail770 I like the column order you have there. It might make sense to highlight the "Deployed" sensors so they are easier to see? Do we ever have other sensor types listed other than Pressure Transducer? If it is the only one used I am not sure that column is needed then.

Just wondering why they would want to see "Deployed" sensors? To remind them to retrieve the sensor, update the status, what? If it is super important you couldf default the table to sort the "Deployed" status first.

**Comment by jprokopec** [comment]
@chaqazarad You're right, it is a good status check on the sensor in the database. How is it sorting first now? I would say event date or status should default first in the list.

**Comment by chaqazarad** [comment]
Sorry just to clarify you mentioned that we might want to highlight or bold the Deployed status. From a users perspective why would they want that status highlighted over the other statuses?

**Comment by jprokopec** [comment]
To make sure their status's are correct. Right now it is easy to miss a deployed status from that list. From the screen shot Abby sent there is a sensor that says deployed from a 2017 event. I am guessing it is still not deployed and is either retrieved or lost. I think highlighting it may give the user pause to check if it was correct.

**Comment by chaqazarad** [comment]
Got it thank you that makes sense. Then I think we could default sort the table by that column. Maybe [Deployed > Retrieved > Proposed > Lost]. Would want to consider the order statuses would appear based on the default sorting then what status would/should show when you reverse sorting.

**Pull request merged**
